version: '2'
networks:
  possumnet:

services:
#   apidocs:
#     build:
#       context: ./apidocs
#       dockerfile: Dockerfile.apidocs
#     image: conjur-apidocs
#     ports:
#       - 3000:3000
#     volumes:
#       - ./apidocs/src:/home/node/src
# 
  sol:
    networks:
      - possumnet
    build: .
    entrypoint: /opt/possum/create.sh
    
  sirius:
    networks:
      - possumnet
    build: .
    entrypoint: /opt/possum/create.sh

  centauri:
    build: .

  possum:
#    image: conjurinc/possum
    networks:
      - possumnet
    build:
      context: .
    command: server -p 80
    environment:
      CONJUR_DATA_KEY: cYnWFEGVxiPzVB7tRX1VfVXrar1to0UhvPY9XrNM0P4=
      CONJUR_ADMIN_PASSWORD: secret

  possum-sol:
    extends:
      service: possum
    depends_on: [sol]
    environment:
      DATABASE_URL: postgres://postgres@sol/possum
    volumes:
      - ./policy:/policy
    ports:
      - "80:80"

  possum-sirius:
    extends:
      service: possum
    depends_on: [sirius]
    environment:
      DATABASE_URL: postgres://postgres@sirius/possum

  possum-centauri:
    extends:
      service: possum
    depends_on: [centauri]
    environment:
      DATABASE_URL: postgres://postgres@centauri/possum

  #python-api:
    #build: ../api-python
    #volumes:
      #- ../api-python:/app:ro
