version: "3"
services:
  pg:
    image: postgres:9.3

  conjur:
    image: conjur-dev
    environment:
      CONJUR_APPLIANCE_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_ADMIN_PASSWORD: admin
      CONJUR_AUTHENTICATORS:
      CONJUR_ACCOUNT: cucumber
      CONJUR_PASSWORD_ALICE: secret
      CONJUR_DATA_KEY:
      RAILS_ENV:
      CONJUR_AUTHENTICATORS: authn-ldap/test
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
    - ..:/src/conjur-server
    - ../../conjur-policy-parser:/src/conjur-policy-parser
    - authn-local:/run/authn-local
    links:
    - pg:pg
    - ldap-server

  cucumber:
    image: conjur-dev
    entrypoint: bash
    environment:
      LDAP_URI: ldap://ldap-server:389
      LDAP_BASE: dc=conjur,dc=net
      CONJUR_APPLIANCE_URL: http://conjur:3000
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_ADMIN_PASSWORD: admin
      CONJUR_DATA_KEY:
      RAILS_ENV:
    volumes:
      - ..:/src/conjur-server
      - authn-local:/run/authn-local
    links:
      - conjur:conjur
      - pg:pg

  client:
    image: conjurinc/cli5
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: http://conjur:3000
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
    links:
    - conjur:conjur
    volumes:
    - ..:/src/conjur-server

  ldap-server:
    image: osixia/openldap
    command: --copy-service
    environment:
      - LDAP_ORGANISATION="ACME Software"
      - LDAP_DOMAIN="softdept.acme.int"
      - LDAP_BASE_DN="dc=conjur,dc=net"
      - LDAP_ADMIN_PASSWORD="password"
    volumes:
      - ../lib/authenticators/authn_ldap/ci/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom


volumes:
  authn-local:
