---
apiVersion: v1
kind: Service
metadata:
  name: conjur
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: conjur
---
apiVersion: v1
kind: Pod
metadata:
  name: conjur
  labels:
    app: conjur
spec:
  containers:
  - image: conjur
    imagePullPolicy: IfNotPresent
    name: conjur
    args: [ server ]
    env:
    - name: DATABASE_URL
      value: postgres://postgres@pg/postgres
    - name: RAILS_ENV
      value: development
    - name: CONJUR_DATA_KEY
      value: LSiMFizXpMBkav5V4sYYs8mrcdhOjoiyB4iCFjhwbt4=

  - image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent
    name: kubectl
    command: [ kubectl, proxy, "-p", "8080" ]
