---
apiVersion: v1
kind: Service
metadata:
  name: conjur-dev
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: conjur-dev
---
apiVersion: v1
kind: Pod
metadata:
  name: conjur-dev
  labels:
    app: conjur-dev
spec:
  containers:
  - image: conjur-dev
    imagePullPolicy: IfNotPresent
    name: conjur
    command: [ sleep ]
    args: [ infinity ]
    env:
    - name: DATABASE_URL
      value: postgres://postgres@pg/postgres
    - name: RAILS_ENV
      value: development
    - name: CONJUR_DATA_KEY
      value: LSiMFizXpMBkav5V4sYYs8mrcdhOjoiyB4iCFjhwbt4=

  - image: lachlanevenson/k8s-kubectl
    imagePullPolicy: IfNotPresent
    name: kubectl
    command: [ kubectl, proxy, "-p", "8080" ]
