---
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  ports:
  - port: 5432
  selector:
    app: pg
---
apiVersion: v1
kind: Pod
metadata:
  name: pg
  labels:
    app: pg
spec:
  containers:
  - image: postgres:9.4
    name: pg
    imagePullPolicy: IfNotPresent
